/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/dapr/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subscriptions */
        get: operations["_get_subscriptions_dapr_subscribe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/upstream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upstream
         * @description What ``name`` was derived from (provenance).
         *
         *     Gated on ``can_get_metadata`` for ``name``; related datasets the caller may not see are
         *     dropped so the graph can't disclose tables outside its reach.
         */
        get: operations["get_upstream_datasets__name__upstream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/downstream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Downstream
         * @description What derives from ``name`` (impact). Gated; non-visible related datasets are dropped.
         */
        get: operations["get_downstream_datasets__name__downstream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/producers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Producers
         * @description The runs that wrote ``name`` — who / when / how. Gated on ``can_get_metadata``.
         */
        get: operations["get_producers_datasets__name__producers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/creator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Creator
         * @description Who created ``name`` (the verified catalog principal). Gated on ``can_get_metadata``.
         */
        get: operations["get_creator_datasets__name__creator_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Schema
         * @description The persisted column schema for ``name`` — at ``?version=N`` if given, else the latest. (#24)
         *
         *     Captured from the standard ``SchemaDatasetFacet`` at ingest and stored per-version on the ``WROTE``
         *     edge (previously the facet was received and discarded). Gated on ``can_get_metadata`` for ``name``;
         *     this is the prerequisite for column-level lineage and powers schema-diffing between Lance versions.
         */
        get: operations["get_schema_datasets__name__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description The connected lineage subgraph around ``name`` (nodes + edges) for a DAG view.
         *
         *     Nodes the caller may not see (and edges touching them) are dropped; the requested ``name``
         *     is already authorized by the route gate.
         */
        get: operations["get_graph_datasets__name__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Datasets
         * @description Browse every dataset the caller may see — the lineage catalog's landing list.
         *
         *     Governed (a dataset is shown only if the caller ``can_get_metadata`` on it), optionally filtered by
         *     ``?namespace=`` / ``?tag=``, and paginated over the *visible* set. This is the entry point the graph
         *     reads (``/datasets/{name}/...``) needed but could not provide — you no longer must know a name first.
         */
        get: operations["list_datasets_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Governed search over the discovery estate (P1 Search tier 1, 2026-07-11).
         *
         *     Case-insensitive substring over dataset NAMES, NAMESPACES, governance TAGS, and the CURRENT
         *     COLUMN inventory — each hit says WHY it matched (``name`` / ``namespace`` / ``tag:…`` /
         *     ``column:…``), so "which tables have an embedding column" and "what's in layer=gold" are one
         *     query. Governance is identical to ``/datasets``: the visibility filter runs over the FULL hit
         *     set BEFORE the limit, so search can never disclose (or even count) tables outside the caller's
         *     reach. 📌 Tier 2 (Lance FTS + FLAT vector content search, the rask pattern) stays decision-
         *     pinned in todo §9 behind its measured recall gate — this tier is metadata-only by design.
         */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description The jobs (compute identities) that have run — governed by the datasets each wrote.
         *
         *     A job is shown only if the caller can see every dataset it wrote (a read-only / output-less job is
         *     hidden when auth is on, mirroring how ``/events`` drops a dataset-less row). Auth off → pass-through.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/namespaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Namespaces
         * @description The namespaces containing at least one dataset the caller may see (for a namespace-tree browse).
         *
         *     Derived from the governed dataset set, so a namespace the caller can see no dataset in never appears.
         */
        get: operations["list_namespaces_namespaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/columns/{field}/upstream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Column Upstream
         * @description Column-level provenance (#24): the columns ``name.field`` was (transitively) derived from.
         *
         *     Our deepest moat — field-to-field lineage neither Marquez nor Lakekeeper derives. Gated on
         *     ``can_get_metadata`` for the owning ``name``; related columns whose *owning dataset* the caller can't
         *     see are dropped (a column has no ACL of its own — it inherits its table's), closing the same
         *     transitive-disclosure hole at column resolution. Auth off → pass-through.
         */
        get: operations["get_column_upstream_datasets__name__columns__field__upstream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/columns/{field}/downstream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Column Downstream
         * @description Column-level impact (#24): the columns (transitively) derived from ``name.field``. Gated +
         *     governed exactly like the column upstream view — related columns in datasets the caller can't see
         *     are dropped.
         */
        get: operations["get_column_downstream_datasets__name__columns__field__downstream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dataset Columns
         * @description The column-level lineage subgraph around ``name`` (#24) — the field-to-field analogue of
         *     ``/graph``, for a DAG view of how each column was produced.
         *
         *     Nodes/edges touching a dataset the caller can't see are dropped (an edge needs BOTH endpoints'
         *     datasets visible); ``name``'s own columns are always shown (the route gate authorized it).
         */
        get: operations["get_dataset_columns_datasets__name__columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/datasets/{name}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reconcile
         * @description Does the lineage graph agree with the **actual Lance file on storage**? (#23)
         *
         *     Our moat over format-unaware catalogs (Marquez, Lakekeeper): because we own a Lance lakehouse we
         *     read the real on-disk version and cross-check it against the version the graph recorded on the
         *     ``WROTE`` edge — surfacing a write that bypassed lineage (``storage_ahead``) or a lineage claim
         *     with no data behind it (``missing_on_storage``). Gated on ``can_get_metadata`` for ``name``; the
         *     Lance read runs in the threadpool so the blocking object-store I/O never stalls the event loop.
         */
        get: operations["get_reconcile_datasets__name__reconcile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runs
         * @description Live run-status board — each run's current state folded onto its ``(:Run)`` node in Apache AGE.
         *
         *     **Durable** (survives restart / replica-shared) and **governed** like ``/events`` and the per-dataset
         *     reads: a run is shown only if the caller ``can_get_metadata`` on every dataset it wrote, so the board
         *     can't enumerate dataset names / creators / errors outside the caller's reach. Auth off → pass-through.
         */
        get: operations["get_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Events
         * @description The most-recent ingested OpenLineage events (newest first) — the Marquez-style event feed.
         *
         *     **Durable** (read from Postgres, survives restart / replica-shared) and **governed**: when auth is
         *     on the feed is filtered like the per-dataset reads — an event is shown only if the caller
         *     ``can_get_metadata`` on *every* dataset it references (and a dataset-less event is hidden), so the
         *     audit feed never discloses a table outside the caller's reach. Auth off → pass-through. (#22)
         *
         *     Pagination (additive, defaults = the old behavior): ``after`` = keyset cursor (the previous
         *     page's ``next_cursor``); ``limit`` ≤ 500 (server-capped); ``summary=true`` drops the full-JSONB
         *     ``event`` payload at the SQL layer. The governance filter ALWAYS runs before the slice —
         *     pagination can never disclose a hidden row's CONTENT. ``next_cursor`` is a WINDOW FLOOR, not
         *     necessarily a visible row's seq (on a hidden-dense page it is the fetch window's last seq —
         *     exclusive, so the hidden row itself is never returned; bare seq numbers were already inferable
         *     from gaps in the pre-pagination feed, so this adds no new disclosure class — reviewed
         *     2026-07-11).
         */
        get: operations["get_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Event
         * @description Ingest one OpenLineage ``RunEvent`` into the lineage graph.
         *
         *     This is the OpenLineage HTTP-transport default path, so any OpenLineage producer
         *     (our emitter, Airflow, Spark, dbt, …) configured with ``OPENLINEAGE_URL`` pointed
         *     here ingests with no glue — the lightweight-Marquez contract.
         *
         *     When OIDC is enabled the ``CurrentToken`` dependency requires a verified bearer token
         *     (401 otherwise), :func:`~lineage.api.fga_deps.enforce_author` binds the run author to that
         *     token's subject (no self-asserted identity), and :func:`~lineage.api.fga_deps.enforce_output_authz`
         *     requires ``can_write_data`` on every output dataset (a producer can't record provenance for a table
         *     it can't write). Both are no-ops when auth is off.
         */
        post: operations["ingest_event_api_v1_lineage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Livez */
        get: operations["livez_livez_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Gate readiness on the AGE pool — lineage's sole hard dependency — plus the lifecycle flags, so a pod
         *     with an unhealthy pool (or mid-boot / draining) is pulled from rotation instead of serving 500s.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demo Datasets
         * @description The medallion datasets as they currently exist on S3 — schema per Lance version + rows.
         */
        get: operations["demo_datasets_demo_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ColumnEdge
         * @description A field-to-field derivation edge (data flows ``source`` → ``target``); the transformation kind +
         *     the ``masking`` governance bit ride the edge.
         */
        ColumnEdge: {
            /** Source Dataset */
            source_dataset: string;
            /** Source Field */
            source_field: string;
            /** Target Dataset */
            target_dataset: string;
            /** Target Field */
            target_field: string;
            /**
             * Transformation Type
             * @default
             */
            transformation_type: string;
            /**
             * Transformation Subtype
             * @default
             */
            transformation_subtype: string;
            /**
             * Masking
             * @default false
             */
            masking: boolean;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Kind
             * @default derived_from_column
             */
            kind: string;
        };
        /**
         * ColumnGraph
         * @description The column-level lineage subgraph around ``root`` (nodes + edges) — the column analogue of the
         *     dataset ``LineageGraph``, for a field-to-field DAG view.
         */
        ColumnGraph: {
            /** Root */
            root: string;
            /** Columns */
            columns?: components["schemas"]["ColumnNode"][];
            /** Edges */
            edges?: components["schemas"]["ColumnEdge"][];
        };
        /**
         * ColumnNeighbors
         * @description Columns related to ``(dataset, field)`` — its column-level provenance (upstream) or impact.
         */
        ColumnNeighbors: {
            /** Dataset */
            dataset: string;
            /** Field */
            field: string;
            /** Related */
            related?: components["schemas"]["ColumnRef"][];
        };
        /**
         * ColumnNode
         * @description A column node in the column-lineage subgraph.
         */
        ColumnNode: {
            /** Dataset */
            dataset: string;
            /** Field */
            field: string;
            /** Type */
            type?: string | null;
        };
        /**
         * ColumnRef
         * @description A column identified by its owning dataset + field name (#24).
         *
         *     ``dataset`` is REQUIRED and is the governance handle: a column is visible iff the caller can read
         *     its owning ``table:<dataset>``, so column queries filter on it (never on the field).
         */
        ColumnRef: {
            /** Dataset */
            dataset: string;
            /** Field */
            field: string;
            /** Namespace */
            namespace?: string | null;
            /** Type */
            type?: string | null;
        };
        /**
         * Creator
         * @description Who created ``dataset`` — the verified catalog principal at create time (or ``None``).
         */
        Creator: {
            /** Dataset */
            dataset: string;
            /** Creator */
            creator?: string | null;
        };
        /**
         * Dataset
         * @description An OpenLineage dataset (a Lance table / source); ``name`` is the catalog id.
         *
         *     ``facets`` carries the standard OpenLineage dataset facets; we read several:
         *     ``version`` (which Lance version a run produced), ``dataSource`` (where the table
         *     physically lives — the S3-compatible location), and ``tags`` (governance labels).
         */
        Dataset: {
            /** Namespace */
            namespace: string;
            /** Name */
            name: string;
            /** Facets */
            facets?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * DatasetRef
         * @description A dataset node returned from a graph traversal.
         */
        DatasetRef: {
            /** Name */
            name: string;
            /** Namespace */
            namespace?: string | null;
        };
        /**
         * DatasetSchema
         * @description The column schema recorded for ``dataset`` at ``version`` (the ``WROTE`` edge's schema). (#24)
         *
         *     ``version`` is the Lance version this schema belongs to; ``None`` with empty ``fields`` means no
         *     schema has been persisted for the dataset (or the requested version) yet.
         */
        DatasetSchema: {
            /** Dataset */
            dataset: string;
            /** Version */
            version?: number | null;
            /** Fields */
            fields?: components["schemas"]["SchemaField"][];
        };
        /**
         * DatasetSummary
         * @description A dataset as it appears in the browse list — its id, namespace, and governance tags.
         */
        DatasetSummary: {
            /** Name */
            name: string;
            /** Namespace */
            namespace?: string | null;
            /** Tags */
            tags?: string[];
        };
        /**
         * Datasets
         * @description A governed, paginated page of datasets the caller may see (the lineage catalog landing list).
         *
         *     ``total`` is the count of *visible* datasets before the page slice — so a UI can show "X–Y of total".
         */
        Datasets: {
            /** Datasets */
            datasets: components["schemas"]["DatasetSummary"][];
            /** Total */
            total: number;
        };
        /**
         * DemoDataset
         * @description A peek at a real Lance dataset on S3 — what's actually in storage and how it evolved.
         */
        DemoDataset: {
            /** Name */
            name: string;
            /** Uri */
            uri: string;
            /** Exists */
            exists: boolean;
            /** Current Version */
            current_version?: number | null;
            /** Row Count */
            row_count?: number | null;
            /** Versions */
            versions?: components["schemas"]["DemoVersion"][];
            /** Lineage Jsonb */
            lineage_jsonb?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /**
         * DemoDatasets
         * @description The medallion datasets as they currently exist on S3 (demo data peek).
         */
        DemoDatasets: {
            /** Datasets */
            datasets: components["schemas"]["DemoDataset"][];
        };
        /**
         * DemoField
         * @description A column of a Lance dataset version (name + Arrow type).
         */
        DemoField: {
            /** Name */
            name: string;
            /** Type */
            type: string;
        };
        /**
         * DemoVersion
         * @description One Lance version of a dataset — its number, time, and schema at that version.
         */
        DemoVersion: {
            /** Version */
            version: number;
            /** Timestamp */
            timestamp?: string | null;
            /** Fields */
            fields?: components["schemas"]["DemoField"][];
        };
        /**
         * EventRecord
         * @description One ingested OpenLineage event, Marquez-style (summary + the full event with facets).
         */
        EventRecord: {
            /** Seq */
            seq: number;
            /** Event Type */
            event_type?: string | null;
            /** Event Time */
            event_time?: string | null;
            /** Job */
            job?: string | null;
            /** Author */
            author?: string | null;
            /** Inputs */
            inputs?: string[];
            /** Outputs */
            outputs?: string[];
            /** Event */
            event: {
                [key: string]: unknown;
            };
        };
        /**
         * Events
         * @description The most-recent ingested OpenLineage events (newest first).
         *
         *     ``next_cursor`` (additive, 2026-07-11): pass back as ``?after=`` to page OLDER events (keyset
         *     over ``seq``). ``None`` = the feed is exhausted.
         */
        Events: {
            /** Events */
            events: components["schemas"]["EventRecord"][];
            /** Next Cursor */
            next_cursor?: number | null;
        };
        /**
         * GraphEdge
         * @description A dataset-level lineage edge: ``source`` is derived from ``target``.
         */
        GraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Kind
             * @default derived_from
             */
            kind: string;
        };
        /**
         * GraphNode
         * @description A dataset node in the lineage graph (``id`` is the catalog table id).
         *
         *     ``source_uri`` is where the table physically lives (the S3-compatible location, from
         *     the ``dataSource`` facet) and ``tags`` are its governance labels (from the ``tags`` facet).
         */
        GraphNode: {
            /** Id */
            id: string;
            /** Namespace */
            namespace?: string | null;
            /**
             * Kind
             * @default dataset
             */
            kind: string;
            /** Source Uri */
            source_uri?: string | null;
            /** Tags */
            tags?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Job
         * @description The compute job that produced a run — for us a Ray job (Ray is the compute engine).
         *
         *     ``facets`` carries the standard ``ownership`` (who owns the job) and ``jobType``
         *     (``processingType`` BATCH/STREAMING, ``integration`` = RAY, ``jobType`` = ETL /
         *     TRANSFORMATION) facets.
         */
        Job: {
            /** Namespace */
            namespace: string;
            /** Name */
            name: string;
            /** Facets */
            facets?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * JobSummary
         * @description A job (compute identity) that has run, with the datasets it wrote — its governance handle.
         */
        JobSummary: {
            /** Namespace */
            namespace?: string | null;
            /** Name */
            name: string;
            /** Outputs */
            outputs?: string[];
        };
        /**
         * Jobs
         * @description The jobs the caller may see (governed by the datasets each wrote).
         */
        Jobs: {
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
            /** Total */
            total: number;
        };
        /**
         * LineageGraph
         * @description The connected lineage subgraph around ``root`` — nodes + edges for a DAG view.
         *
         *     Mirrors what Marquez's graph endpoint feeds its UI, trimmed to the dataset-level
         *     ``DERIVED_FROM`` lineage we model.
         */
        LineageGraph: {
            /** Root */
            root: string;
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /**
         * Namespaces
         * @description The namespaces containing at least one dataset the caller may see.
         */
        Namespaces: {
            /** Namespaces */
            namespaces: string[];
        };
        /**
         * Neighbors
         * @description Datasets related to ``dataset`` (upstream provenance or downstream impact).
         */
        Neighbors: {
            /** Dataset */
            dataset: string;
            /** Related */
            related: components["schemas"]["DatasetRef"][];
        };
        /**
         * ProducerInfo
         * @description A run that wrote (or attempted to write) a dataset — who / when / how / version / measured size.
         *
         *     A **failed** run (``event_type`` FAIL/ABORT) appears here too, with no
         *     ``dataset_version`` and an ``error_message`` — it tried but produced no data.
         *
         *     ``row_count`` / ``size_bytes`` are the runtime-measured output statistics the compute recorded for
         *     this write (the rows + on-disk bytes it actually produced, from the standard ``outputStatistics``
         *     facet); ``None`` when the run was a dummy emit (no compute) or a failure (no data produced).
         *
         *     ``quality_passed`` is the validator gate's verdict (all assertions succeeded) and ``quality_assertions``
         *     the checks it ran (from the standard ``dataQualityAssertions`` facet); ``quality_passed=False`` with a
         *     real ``dataset_version`` is the auditable record of a batch the gate blocked from promotion. Both are
         *     ``None`` / empty when the quality gate did not run.
         */
        ProducerInfo: {
            /** Run Id */
            run_id: string;
            /** Author */
            author?: string | null;
            /** Event Time */
            event_time?: string | null;
            /** Event Type */
            event_type?: string | null;
            /** Dataset Version */
            dataset_version?: string | null;
            /** Producer */
            producer?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Row Count */
            row_count?: number | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /** Quality Passed */
            quality_passed?: boolean | null;
            /** Quality Assertions */
            quality_assertions?: {
                [key: string]: unknown;
            }[];
            /** Operation */
            operation?: string | null;
        };
        /**
         * Producers
         * @description The runs that produced ``dataset``.
         */
        Producers: {
            /** Dataset */
            dataset: string;
            /** Producers */
            producers: components["schemas"]["ProducerInfo"][];
        };
        /**
         * ReconcileState
         * @description Result of reconciling the lineage graph's recorded version against the on-disk Lance version.
         * @enum {string}
         */
        ReconcileState: "in_sync" | "storage_ahead" | "graph_ahead" | "untracked" | "missing_on_storage" | "absent";
        /**
         * ReconcileStatus
         * @description Whether a dataset's lineage-graph version matches its actual on-disk Lance version (#23).
         *
         *     ``dangling_blob_columns`` (§9 P1 lifecycle, 2026-07-12) is the POINTER-health axis the version
         *     comparison can't see: a blob-v2 column whose payloads no longer dereference (external object
         *     deleted, bucket wiped) leaves the version untouched — a dataset can be ``in_sync`` and still
         *     unreadable. Non-empty = those columns failed a real 1-byte probe read.
         */
        ReconcileStatus: {
            /** Dataset */
            dataset: string;
            /** Graph Version */
            graph_version?: number | null;
            /** Storage Version */
            storage_version?: number | null;
            /** In Sync */
            in_sync: boolean;
            status: components["schemas"]["ReconcileState"];
            /**
             * Dangling Blob Columns
             * @default []
             */
            dangling_blob_columns: string[];
        };
        /**
         * Run
         * @description A single run of a job. ``facets.author`` carries the OIDC sub when present.
         */
        Run: {
            /** Runid */
            runId: string;
            /** Facets */
            facets?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        /**
         * RunEvent
         * @description An OpenLineage run event (START/RUNNING/COMPLETE/FAIL/ABORT) with its inputs and outputs.
         */
        RunEvent: {
            /** Eventtype */
            eventType: string;
            /** Eventtime */
            eventTime: string;
            /** Producer */
            producer?: string | null;
            run: components["schemas"]["Run"];
            job: components["schemas"]["Job"];
            /** Inputs */
            inputs?: components["schemas"]["Dataset"][];
            /** Outputs */
            outputs?: components["schemas"]["Dataset"][];
        } & {
            [key: string]: unknown;
        };
        /**
         * RunStatus
         * @description The *current* status of a run, folded from its OpenLineage lifecycle events.
         *
         *     Unlike the provenance graph (terminal-only), this is the live "where are we now" view:
         *     ``state`` is the latest run state (START→RUNNING→COMPLETE/FAIL), with progress + error.
         */
        RunStatus: {
            /** Run Id */
            run_id: string;
            /** Job */
            job?: string | null;
            /** Author */
            author?: string | null;
            /** State */
            state?: string | null;
            /** Outputs */
            outputs?: string[];
            /** Progress Done */
            progress_done?: number | null;
            /** Progress Total */
            progress_total?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Events
             * @default 0
             */
            events: number;
            /** Operation */
            operation?: string | null;
        };
        /**
         * Runs
         * @description Live run-status board (most-recently-active first).
         */
        Runs: {
            /** Runs */
            runs: components["schemas"]["RunStatus"][];
        };
        /**
         * SchemaField
         * @description One column in a dataset's persisted per-version schema (from the standard ``schema`` facet).
         */
        SchemaField: {
            /** Name */
            name: string;
            /**
             * Type
             * @default
             */
            type: string;
            /** Description */
            description?: string | null;
        };
        /**
         * SearchHit
         * @description One /search result: the dataset + WHY it matched (name / namespace / tag:* / column:*).
         */
        SearchHit: {
            /** Name */
            name: string;
            /** Namespace */
            namespace?: string | null;
            /** Tags */
            tags?: string[];
            /** Matches */
            matches?: string[];
        };
        /**
         * SearchResults
         * @description Governed search results (P1 Search tier 1 — substring over the discovery estate).
         */
        SearchResults: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchHit"][];
            /** Total */
            total: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    _get_subscriptions_dapr_subscribe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_upstream_datasets__name__upstream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighbors"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_downstream_datasets__name__downstream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Neighbors"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_producers_datasets__name__producers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Producers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_creator_datasets__name__creator_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Creator"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schema_datasets__name__schema_get: {
        parameters: {
            query?: {
                version?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_datasets__name__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineageGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_datasets_get: {
        parameters: {
            query?: {
                namespace?: string | null;
                tag?: string | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Datasets"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jobs"];
                };
            };
        };
    };
    list_namespaces_namespaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Namespaces"];
                };
            };
        };
    };
    get_column_upstream_datasets__name__columns__field__upstream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnNeighbors"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_column_downstream_datasets__name__columns__field__downstream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                field: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnNeighbors"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dataset_columns_datasets__name__columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ColumnGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reconcile_datasets__name__reconcile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconcileStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Runs"];
                };
            };
        };
    };
    get_events_events_get: {
        parameters: {
            query?: {
                after?: number | null;
                limit?: number;
                summary?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Events"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_event_api_v1_lineage_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunEvent"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    livez_livez_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    demo_datasets_demo_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoDatasets"];
                };
            };
        };
    };
}
